version: '3.7'

services:
  terraform:
    build:
      context: .
      args:
        TERRAFORM_VERSION: 1.0.5
        PACKER_VERSION: 1.7.0
    working_dir: /home/terraform
    env_file:
      - .env
    volumes:
      - ./:/home