version: '3.7'

services:
  agent:
    image: portainer/agent:2.1.0
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global

  portainer:
    image: portainer/portainer-ce:2.1.1
    command: -H tcp://tasks.agent:9001 --tlsskipverify --admin-password='${portainer_admin_password}'
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - ${shared_volume_mountpoint}/portainer:/data
    networks:
      - agent_network
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1      
      placement:
        constraints:
          - node.role == manager      
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer_portainer.rule=Host(`portainer.${swarm_domain}`)"
        - "traefik.http.services.portainer_portainer.loadbalancer.server.port=9000"
        - "traefik.http.routers.portainer_portainer.entrypoints=web"        

networks:
  agent_network:
    driver: overlay
    attachable: true
  traefik-public:
    external: true